name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-cache: 'pip'

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev libgstreamer1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libgstreamer-plugins-base1.0-dev libasound2-dev
          pip install --upgrade buildozer cython

      - name: Build with Buildozer
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Tactical-Proxy-APK
          path: bin/*.apk
          
